

module AbsNumbers where

-- Haskell module generated by the BNF converter




data Exp
    = Plus Exp Exp
    | Sub Exp Exp
    | Times Exp Exp
    | Num Integer
    | Divide Exp Exp
    | Exponent Exp Exp
    | Modulus Exp Exp
    | Negative Exp
    | Min Exp Exp
    | Max Exp Exp
  deriving (Eq, Ord, Show, Read)

